package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 6, 2016 12:05:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailsId generated by hbm2java
 */
@Embeddable
public class OrderDetailsId  implements java.io.Serializable {


     private int orderId;
     private int menuItemId;

    public OrderDetailsId() {
    }

    public OrderDetailsId(int orderId, int menuItemId) {
       this.orderId = orderId;
       this.menuItemId = menuItemId;
    }
   


    @Column(name="order_id", nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }


    @Column(name="menu_item_id", nullable=false)
    public int getMenuItemId() {
        return this.menuItemId;
    }
    
    public void setMenuItemId(int menuItemId) {
        this.menuItemId = menuItemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderDetailsId) ) return false;
		 OrderDetailsId castOther = ( OrderDetailsId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getMenuItemId()==castOther.getMenuItemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getMenuItemId();
         return result;
   }   


}


