package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Catering generated by hbm2java
 */
public class Catering implements java.io.Serializable {

	private int cateringId;
	private String description;
	private Date creationDate;
	private int openTime;
	private Date deliveryDate;
	private float budget;
	private Set categories = new HashSet(0);

	public Catering() {
	}

	public Catering(int cateringId, String description, Date creationDate,
			int openTime, Date deliveryDate, float budget) {
		this.cateringId = cateringId;
		this.description = description;
		this.creationDate = creationDate;
		this.openTime = openTime;
		this.deliveryDate = deliveryDate;
		this.budget = budget;
	}

	public Catering(int cateringId, String description, Date creationDate,
			int openTime, Date deliveryDate, float budget, Set categories) {
		this.cateringId = cateringId;
		this.description = description;
		this.creationDate = creationDate;
		this.openTime = openTime;
		this.deliveryDate = deliveryDate;
		this.budget = budget;
		this.categories = categories;
	}

	public int getCateringId() {
		return this.cateringId;
	}

	public void setCateringId(int cateringId) {
		this.cateringId = cateringId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public int getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(int openTime) {
		this.openTime = openTime;
	}

	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public float getBudget() {
		return this.budget;
	}

	public void setBudget(float budget) {
		this.budget = budget;
	}

	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

}
