package com.iti.jet.gp.etbo5ly.model.pojos;


// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

/**
 * CateringDetails generated by hbm2java
 */
public class CateringDetails implements java.io.Serializable {

	private int cateringDetailsId;
	private Order order;
	private String name;
	private String description;
	private String quantity;
	private Float price;

	public CateringDetails() {
	}

	public CateringDetails(int cateringDetailsId, Order order) {
		this.cateringDetailsId = cateringDetailsId;
		this.order = order;
	}

	public CateringDetails(int cateringDetailsId, Order order, String name,
			String description, String quantity, Float price) {
		this.cateringDetailsId = cateringDetailsId;
		this.order = order;
		this.name = name;
		this.description = description;
		this.quantity = quantity;
		this.price = price;
	}

	public int getCateringDetailsId() {
		return this.cateringDetailsId;
	}

	public void setCateringDetailsId(int cateringDetailsId) {
		this.cateringDetailsId = cateringDetailsId;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

}
