package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private int categoryId;
	private String nameEn;
	private String nameAr;
	private Set caterings = new HashSet(0);
	private Set menuItems = new HashSet(0);

	public Category() {
	}

	public Category(int categoryId) {
		this.categoryId = categoryId;
	}

	public Category(int categoryId, String nameEn, String nameAr,
			Set caterings, Set menuItems) {
		this.categoryId = categoryId;
		this.nameEn = nameEn;
		this.nameAr = nameAr;
		this.caterings = caterings;
		this.menuItems = menuItems;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public String getNameAr() {
		return this.nameAr;
	}

	public void setNameAr(String nameAr) {
		this.nameAr = nameAr;
	}

	public Set getCaterings() {
		return this.caterings;
	}

	public void setCaterings(Set caterings) {
		this.caterings = caterings;
	}

	public Set getMenuItems() {
		return this.menuItems;
	}

	public void setMenuItems(Set menuItems) {
		this.menuItems = menuItems;
	}

}
