package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cook generated by hbm2java
 */
public class Cook extends User implements java.io.Serializable {

	private CookStatus cookStatus;
	private Date startWorkingHours;
	private Date endWorkingHours;
	private Set documents = new HashSet(0);
	private Set menuItems = new HashSet(0);

	public Cook() {
	}

	public Cook(CookStatus cookStatus) {
		this.cookStatus = cookStatus;
	}

	public Cook( CookStatus cookStatus, Date startWorkingHours,
			Date endWorkingHours, Set documents, Set menuItems) {
		this.cookStatus = cookStatus;
		this.startWorkingHours = startWorkingHours;
		this.endWorkingHours = endWorkingHours;
		this.documents = documents;
		this.menuItems = menuItems;
	}


	public CookStatus getCookStatus() {
		return this.cookStatus;
	}

	public void setCookStatus(CookStatus cookStatus) {
		this.cookStatus = cookStatus;
	}

	public Date getStartWorkingHours() {
		return this.startWorkingHours;
	}

	public void setStartWorkingHours(Date startWorkingHours) {
		this.startWorkingHours = startWorkingHours;
	}

	public Date getEndWorkingHours() {
		return this.endWorkingHours;
	}

	public void setEndWorkingHours(Date endWorkingHours) {
		this.endWorkingHours = endWorkingHours;
	}

	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

	public Set getMenuItems() {
		return this.menuItems;
	}

	public void setMenuItems(Set menuItems) {
		this.menuItems = menuItems;
	}

}
