package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CookStatus generated by hbm2java
 */
public class CookStatus implements java.io.Serializable {

	private int statusId;
	private String status;
	private Set cooks = new HashSet(0);

	public CookStatus() {
	}

	public CookStatus(int statusId, String status) {
		this.statusId = statusId;
		this.status = status;
	}

	public CookStatus(int statusId, String status, Set cooks) {
		this.statusId = statusId;
		this.status = status;
		this.cooks = cooks;
	}

	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getCooks() {
		return this.cooks;
	}

	public void setCooks(Set cooks) {
		this.cooks = cooks;
	}

}
