package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

/**
 * Customer generated by hbm2java
 */
public class Customer extends User implements java.io.Serializable {


	public Customer() {
	}

	

}
