package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentType generated by hbm2java
 */
public class DocumentType implements java.io.Serializable {

	private int documentTypeId;
	private String type;
	private Set documents = new HashSet(0);  // why ?

	public DocumentType() {
	}

	public DocumentType(int documentTypeId, String type) {
		this.documentTypeId = documentTypeId;
		this.type = type;
	}

	public DocumentType(int documentTypeId, String type, Set documents) {
		this.documentTypeId = documentTypeId;
		this.type = type;
		this.documents = documents;
	}

	public int getDocumentTypeId() {
		return this.documentTypeId;
	}

	public void setDocumentTypeId(int documentTypeId) {
		this.documentTypeId = documentTypeId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

}
