package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * MenuItems generated by hbm2java
 */
public class MenuItems implements java.io.Serializable {

	private int itemId;
	private Cook cook;
	private String nameEn;
	private String nameAr;
	private float price;
	private byte[] image;
	private String descriptionEn;
	private String descriptionAr;
	private Short itemRate;
	private Set tagses = new HashSet(0);
	private Set orderDetailses = new HashSet(0);
	private Set categories = new HashSet(0);

	public MenuItems() {
	}

	public MenuItems(int itemId, Cook cook, String nameEn, String nameAr,
			float price, byte[] image, String descriptionEn,
			String descriptionAr) {
		this.itemId = itemId;
		this.cook = cook;
		this.nameEn = nameEn;
		this.nameAr = nameAr;
		this.price = price;
		this.image = image;
		this.descriptionEn = descriptionEn;
		this.descriptionAr = descriptionAr;
	}

	public MenuItems(int itemId, Cook cook, String nameEn, String nameAr,
			float price, byte[] image, String descriptionEn,
			String descriptionAr, Short itemRate, Set tagses,
			Set orderDetailses, Set categories) {
		this.itemId = itemId;
		this.cook = cook;
		this.nameEn = nameEn;
		this.nameAr = nameAr;
		this.price = price;
		this.image = image;
		this.descriptionEn = descriptionEn;
		this.descriptionAr = descriptionAr;
		this.itemRate = itemRate;
		this.tagses = tagses;
		this.orderDetailses = orderDetailses;
		this.categories = categories;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public Cook getCook() {
		return this.cook;
	}

	public void setCook(Cook cook) {
		this.cook = cook;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public String getNameAr() {
		return this.nameAr;
	}

	public void setNameAr(String nameAr) {
		this.nameAr = nameAr;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getDescriptionEn() {
		return this.descriptionEn;
	}

	public void setDescriptionEn(String descriptionEn) {
		this.descriptionEn = descriptionEn;
	}

	public String getDescriptionAr() {
		return this.descriptionAr;
	}

	public void setDescriptionAr(String descriptionAr) {
		this.descriptionAr = descriptionAr;
	}

	public Short getItemRate() {
		return this.itemRate;
	}

	public void setItemRate(Short itemRate) {
		this.itemRate = itemRate;
	}

	public Set getTagses() {
		return this.tagses;
	}

	public void setTagses(Set tagses) {
		this.tagses = tagses;
	}

	public Set getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

}
