package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

/**
 * OrderDetailsId generated by hbm2java
 */
public class OrderDetailsId implements java.io.Serializable {

	private int orderId;
	private int menuItemId;

	public OrderDetailsId() {
	}

	public OrderDetailsId(int orderId, int menuItemId) {
		this.orderId = orderId;
		this.menuItemId = menuItemId;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public int getMenuItemId() {
		return this.menuItemId;
	}

	public void setMenuItemId(int menuItemId) {
		this.menuItemId = menuItemId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailsId))
			return false;
		OrderDetailsId castOther = (OrderDetailsId) other;

		return (this.getOrderId() == castOther.getOrderId())
				&& (this.getMenuItemId() == castOther.getMenuItemId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getMenuItemId();
		return result;
	}

}
