package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer orderId;
	private User userByCustomerId;
	private User userByCookId;
	private String location;
	private Date orderTime;
	private int duration;
	private Short customerRating;
	private String orderComment;
	private Short cookRating;
	private String cookComment;
	private String type;
	private Set orderDetailses = new HashSet(0);
	private Set cateringDetailses = new HashSet(0);
	private Set statusHasOrders = new HashSet(0);

	public Order() {
	}

	public Order(User userByCustomerId, User userByCookId, String location,
			Date orderTime, int duration) {
		this.userByCustomerId = userByCustomerId;
		this.userByCookId = userByCookId;
		this.location = location;
		this.orderTime = orderTime;
		this.duration = duration;
	}

	public Order(User userByCustomerId, User userByCookId, String location,
			Date orderTime, int duration, Short customerRating,
			String orderComment, Short cookRating, String cookComment,
			String type, Set orderDetailses, Set cateringDetailses,
			Set statusHasOrders) {
		this.userByCustomerId = userByCustomerId;
		this.userByCookId = userByCookId;
		this.location = location;
		this.orderTime = orderTime;
		this.duration = duration;
		this.customerRating = customerRating;
		this.orderComment = orderComment;
		this.cookRating = cookRating;
		this.cookComment = cookComment;
		this.type = type;
		this.orderDetailses = orderDetailses;
		this.cateringDetailses = cateringDetailses;
		this.statusHasOrders = statusHasOrders;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public User getUserByCustomerId() {
		return this.userByCustomerId;
	}

	public void setUserByCustomerId(User userByCustomerId) {
		this.userByCustomerId = userByCustomerId;
	}

	public User getUserByCookId() {
		return this.userByCookId;
	}

	public void setUserByCookId(User userByCookId) {
		this.userByCookId = userByCookId;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public Short getCustomerRating() {
		return this.customerRating;
	}

	public void setCustomerRating(Short customerRating) {
		this.customerRating = customerRating;
	}

	public String getOrderComment() {
		return this.orderComment;
	}

	public void setOrderComment(String orderComment) {
		this.orderComment = orderComment;
	}

	public Short getCookRating() {
		return this.cookRating;
	}

	public void setCookRating(Short cookRating) {
		this.cookRating = cookRating;
	}

	public String getCookComment() {
		return this.cookComment;
	}

	public void setCookComment(String cookComment) {
		this.cookComment = cookComment;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

	public Set getCateringDetailses() {
		return this.cateringDetailses;
	}

	public void setCateringDetailses(Set cateringDetailses) {
		this.cateringDetailses = cateringDetailses;
	}

	public Set getStatusHasOrders() {
		return this.statusHasOrders;
	}

	public void setStatusHasOrders(Set statusHasOrders) {
		this.statusHasOrders = statusHasOrders;
	}

}
