package com.iti.jet.gp.etbo5ly.model.pojos;


// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable {

	private OrderDetailsId id;
	private MenuItems menuItems;
	private Order order;
	private Integer quantity;
	private Float price;
	private Short rating;
	private String comment;

	public OrderDetails() {

	}

	public OrderDetails(OrderDetailsId id, MenuItems menuItems, Order order) {
		this.id = id;
		this.menuItems = menuItems;
		this.order = order;
	}

	public OrderDetails(OrderDetailsId id, MenuItems menuItems, Order order,
			Integer quantity, Float price, Short rating, String comment) {
		this.id = id;
		this.menuItems = menuItems;
		this.order = order;
		this.quantity = quantity;
		this.price = price;
		this.rating = rating;
		this.comment = comment;
	}

	public OrderDetailsId getId() {
		return this.id;
	}

	public void setId(OrderDetailsId id) {
		this.id = id;
	}

	public MenuItems getMenuItems() {
		return this.menuItems;
	}

	public void setMenuItems(MenuItems menuItems) {
		this.menuItems = menuItems;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Short getRating() {
		return this.rating;
	}

	public void setRating(Short rating) {
		this.rating = rating;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
