package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus implements java.io.Serializable {

	private int statusId;
	private String status;
	private Set statusHasOrders = new HashSet(0);

	public OrderStatus() {
	}

	public OrderStatus(int statusId, String status) {
		this.statusId = statusId;
		this.status = status;
	}

	public OrderStatus(int statusId, String status, Set statusHasOrders) {
		this.statusId = statusId;
		this.status = status;
		this.statusHasOrders = statusHasOrders;
	}

	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getStatusHasOrders() {
		return this.statusHasOrders;
	}

	public void setStatusHasOrders(Set statusHasOrders) {
		this.statusHasOrders = statusHasOrders;
	}

}
