package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int id;
	private String role;
	private Set users = new HashSet(0);

	public Role() {
	}

	public Role(int id, String role) {
		this.id = id;
		this.role = role;
	}

	public Role(int id, String role, Set users) {
		this.id = id;
		this.role = role;
		this.users = users;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
