package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * StatusHasOrder generated by hbm2java
 */
public class StatusHasOrder implements java.io.Serializable {

	private StatusHasOrderId id;
	private Order order;
	private OrderStatus orderStatus;
	private Date time;

	public StatusHasOrder() {
	}

	public StatusHasOrder(StatusHasOrderId id, Order order,
			OrderStatus orderStatus, Date time) {
		this.id = id;
		this.order = order;
		this.orderStatus = orderStatus;
		this.time = time;
	}

	public StatusHasOrderId getId() {
		return this.id;
	}

	public void setId(StatusHasOrderId id) {
		this.id = id;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public OrderStatus getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
