package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Tags generated by hbm2java
 */
public class Tags implements java.io.Serializable {

	private int tagId;
	private String tagEn;
	private String tagAr;
	private Set menuItems = new HashSet(0);

	public Tags() {
	}

	public Tags(int tagId) {
		this.tagId = tagId;
	}

	public Tags(int tagId, String tagEn, String tagAr, Set menuItems) {
		this.tagId = tagId;
		this.tagEn = tagEn;
		this.tagAr = tagAr;
		this.menuItems = menuItems;
	}

	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	public String getTagEn() {
		return this.tagEn;
	}

	public void setTagEn(String tagEn) {
		this.tagEn = tagEn;
	}

	public String getTagAr() {
		return this.tagAr;
	}

	public void setTagAr(String tagAr) {
		this.tagAr = tagAr;
	}

	public Set getMenuItems() {
		return this.menuItems;
	}

	public void setMenuItems(Set menuItems) {
		this.menuItems = menuItems;
	}

}
