package com.iti.jet.gp.etbo5ly.model.pojos;

// Generated May 1, 2016 3:52:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String password;
	private Boolean enabled;
	private byte[] image;
	private Date registerationDate;
	private String phone;
	private String address;
	private Set roles = new HashSet(0);
	private Set ordersForCookId = new HashSet(0);
	private Set ordersForCustomerId = new HashSet(0);

	public User() {
	}

	public User(String name, String email, String password, String phone,
			String address) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.phone = phone;
		this.address = address;
	}

	public User(String name, String email, String password, Boolean enabled,
			byte[] image, Date registerationDate, String phone, String address,
			Set roles, Set ordersForCookId, Set ordersForCustomerId) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.enabled = enabled;
		this.image = image;
		this.registerationDate = registerationDate;
		this.phone = phone;
		this.address = address;
		this.roles = roles;
		this.ordersForCookId = ordersForCookId;
		this.ordersForCustomerId = ordersForCustomerId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Date getRegisterationDate() {
		return this.registerationDate;
	}

	public void setRegisterationDate(Date registerationDate) {
		this.registerationDate = registerationDate;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

	public Set getOrdersForCookId() {
		return this.ordersForCookId;
	}

	public void setOrdersForCookId(Set ordersForCookId) {
		this.ordersForCookId = ordersForCookId;
	}

	public Set getOrdersForCustomerId() {
		return this.ordersForCustomerId;
	}

	public void setOrdersForCustomerId(Set ordersForCustomerId) {
		this.ordersForCustomerId = ordersForCustomerId;
	}

}
