package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 6, 2016 12:05:20 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import org.springframework.context.annotation.PropertySource;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category",catalog = "etbo5ly")
public class Category implements java.io.Serializable {

    private int categoryId;
    private String nameEn;
    private String nameAr;
    private Set<Catering> caterings = new HashSet<Catering>(0);
    private Set<MenuItems> menuItems = new HashSet<MenuItems>(0);

    public Category() {
    }

    public Category(int categoryId) {
        this.categoryId = categoryId;
    }

    public Category(int categoryId, String nameEn, String nameAr, Set caterings, Set menuItems) {
        this.categoryId = categoryId;
        this.nameEn = nameEn;
        this.nameAr = nameAr;
        this.caterings = caterings;
        this.menuItems = menuItems;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "category_id", unique = true, nullable = false)
    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    @Column(name = "name_en", length = 45)
    public String getNameEn() {
        return this.nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    @Column(name = "name_ar", length = 45)
    public String getNameAr() {
        return this.nameAr;
    }

    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "catering_has_category", catalog = "mydb", joinColumns = {
        @JoinColumn(name = "category_category_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "catering_catering_id", nullable = false, updatable = false)})
    @JsonIgnore //aljazayeerly- to be igonred when converting from object to json
    public Set<Catering> getCaterings() {
        return this.caterings;
    }

    public void setCaterings(Set<Catering> caterings) {
        this.caterings = caterings;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "category_has_menu_items", catalog = "mydb", joinColumns = {
        @JoinColumn(name = "category_category_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "menu_items_item_id", nullable = false, updatable = false)})
    @JsonIgnore
    public Set<MenuItems> getMenuItems() {
        return this.menuItems;
    }

    public void setMenuItems(Set<MenuItems> menuItems) {
        this.menuItems = menuItems;
    }

}
