package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 6, 2016 12:05:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Catering generated by hbm2java
 */
@Entity
@Table(name="catering"
    ,catalog="mydb"
)
public class Catering  implements java.io.Serializable {


     private int cateringId;
     private String description;
     private Date creationDate;
     private int openTime;
     private Date deliveryDate;
     private float budget;
     private Set<Category> categories = new HashSet<Category>(0);

    public Catering() {
    }

	
    public Catering(int cateringId, String description, Date creationDate, int openTime, Date deliveryDate, float budget) {
        this.cateringId = cateringId;
        this.description = description;
        this.creationDate = creationDate;
        this.openTime = openTime;
        this.deliveryDate = deliveryDate;
        this.budget = budget;
    }
    public Catering(int cateringId, String description, Date creationDate, int openTime, Date deliveryDate, float budget, Set categories) {
       this.cateringId = cateringId;
       this.description = description;
       this.creationDate = creationDate;
       this.openTime = openTime;
       this.deliveryDate = deliveryDate;
       this.budget = budget;
       this.categories = categories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="catering_id", unique=true, nullable=false)
    public int getCateringId() {
        return this.cateringId;
    }
    
    public void setCateringId(int cateringId) {
        this.cateringId = cateringId;
    }

    
    @Column(name="description", nullable=false, length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="open_time", nullable=false)
    public int getOpenTime() {
        return this.openTime;
    }
    
    public void setOpenTime(int openTime) {
        this.openTime = openTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="delivery_date", nullable=false, length=19)
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    
    @Column(name="budget", nullable=false, precision=12, scale=0)
    public float getBudget() {
        return this.budget;
    }
    
    public void setBudget(float budget) {
        this.budget = budget;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="catering_has_category", catalog="mydb", joinColumns = { 
        @JoinColumn(name="catering_catering_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="category_category_id", nullable=false, updatable=false) })
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }




}


