package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 20, 2016 12:10:15 AM by Hibernate Tools 3.6.0

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "etbo5ly"
)
public class City implements java.io.Serializable {

    private int cityId;
    private Country country;
    private String cityName;
    private String cityNameAr;
    private Set<Region> regions = new HashSet<Region>(0);

    public City() {
    }

    public City(int cityId, Country country, String cityName) {
        this.cityId = cityId;
        this.country = country;
        this.cityName = cityName;
    }

    public City(int cityId, Country country, String cityName, String cityNameAr, Set<Region> regions) {
        this.cityId = cityId;
        this.country = country;
        this.cityName = cityName;
        this.cityNameAr = cityNameAr;
        this.regions = regions;
    }

    @Id

    @Column(name = "city_id", unique = true, nullable = false)
    public int getCityId() {
        return this.cityId;
    }

    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "country_id", nullable = false)
    @JsonIgnore
    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    @Column(name = "city_name", nullable = false, length = 45)
    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    @Column(name = "city_name_ar", length = 45)
    public String getCityNameAr() {
        return this.cityNameAr;
    }

    public void setCityNameAr(String cityNameAr) {
        this.cityNameAr = cityNameAr;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "city")
    public Set<Region> getRegions() {
        return this.regions;
    }

    public void setRegions(Set<Region> regions) {
        this.regions = regions;
    }

}
