package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 6, 2016 12:05:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer")
@PrimaryKeyJoinColumn(name="id")
public class Customer  extends User implements java.io.Serializable {


//     private Integer id;

    public Customer() {
    }

   
//      @GeneratedValue(strategy=IDENTITY)
////
////    
//    @Column(name="id", unique=true, nullable=false)
//    public Integer getId() {
//        return this.id;
//    }
    
//    public void setId(Integer id) {
//        this.id = id;
//    }




}


