package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 20, 2016 12:10:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name="order_status"
    ,catalog="etbo5ly"
)
public class OrderStatus  implements java.io.Serializable {


     private Integer statusId;
     private String status;
     private Set<StatusHasOrder> statusHasOrders = new HashSet<StatusHasOrder>(0);

    public OrderStatus() {
    }

	
    public OrderStatus(String status) {
        this.status = status;
    }
    public OrderStatus(String status, Set<StatusHasOrder> statusHasOrders) {
       this.status = status;
       this.statusHasOrders = statusHasOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="status_id", unique=true, nullable=false)
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orderStatus")
    public Set<StatusHasOrder> getStatusHasOrders() {
        return this.statusHasOrders;
    }
    
    public void setStatusHasOrders(Set<StatusHasOrder> statusHasOrders) {
        this.statusHasOrders = statusHasOrders;
    }




}


