package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 6, 2016 12:05:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name="order_status")
public class OrderStatus  implements java.io.Serializable {


     private int statusId;
     private String status;
     private Set<StatusHasOrder> statusHasOrders = new HashSet<StatusHasOrder> (0);

    public OrderStatus() {
    }

	
    public OrderStatus(int statusId, String status) {
        this.statusId = statusId;
        this.status = status;
    }
    public OrderStatus(int statusId, String status, Set statusHasOrders) {
       this.statusId = statusId;
       this.status = status;
       this.statusHasOrders = statusHasOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="status_id", unique=true, nullable=false)
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orderStatus")
    public Set<StatusHasOrder>  getStatusHasOrders() {
        return this.statusHasOrders;
    }
    
    public void setStatusHasOrders(Set<StatusHasOrder>  statusHasOrders) {
        this.statusHasOrders = statusHasOrders;
    }




}


