package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 6, 2016 12:05:20 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name="order_details")
public class OrderDetails  implements java.io.Serializable {


     private OrderDetailsId id;
     private MenuItems menuItems;
     private Order order;
     private Integer quantity;
     private Float price;
     private Short rating;
     private String comment;

    public OrderDetails() {
    }

	
    public OrderDetails(OrderDetailsId id, MenuItems menuItems, Order order) {
        this.id = id;
        this.menuItems = menuItems;
        this.order = order;
    }
    public OrderDetails(OrderDetailsId id, MenuItems menuItems, Order order, Integer quantity, Float price, Short rating, String comment) {
       this.id = id;
       this.menuItems = menuItems;
       this.order = order;
       this.quantity = quantity;
       this.price = price;
       this.rating = rating;
       this.comment = comment;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="order_id", nullable=false) ), 
        @AttributeOverride(name="menuItemId", column=@Column(name="menu_item_id", nullable=false) ) } )
    public OrderDetailsId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menu_item_id", nullable=false, insertable=false, updatable=false)
    public MenuItems getMenuItems() {
        return this.menuItems;
    }
    
    public void setMenuItems(MenuItems menuItems) {
        this.menuItems = menuItems;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false, insertable=false, updatable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", precision=12, scale=0)
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }

    
    @Column(name="rating")
    public Short getRating() {
        return this.rating;
    }
    
    public void setRating(Short rating) {
        this.rating = rating;
    }

    
    @Column(name="comment", length=150)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


