package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 20, 2016 12:10:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="region"
    ,catalog="etbo5ly"
)
public class Region  implements java.io.Serializable {


     private int regionId;
     private City city;
     private String regionName;
     private String regionNameAr;
     private Set<Order> orders = new HashSet<Order>(0);
     private Set<User> users = new HashSet<User>(0);

    public Region() {
    }

	
    public Region(int regionId, City city, String regionName) {
        this.regionId = regionId;
        this.city = city;
        this.regionName = regionName;
    }
    public Region(int regionId, City city, String regionName, String regionNameAr, Set<Order> orders, Set<User> users) {
       this.regionId = regionId;
       this.city = city;
       this.regionName = regionName;
       this.regionNameAr = regionNameAr;
       this.orders = orders;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="region_id", unique=true, nullable=false)
    public int getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(int regionId) {
        this.regionId = regionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_id", nullable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="region_name", nullable=false, length=45)
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    
    @Column(name="region_name_ar", length=45)
    public String getRegionNameAr() {
        return this.regionNameAr;
    }
    
    public void setRegionNameAr(String regionNameAr) {
        this.regionNameAr = regionNameAr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


