package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 6, 2016 12:05:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StatusHasOrderId generated by hbm2java
 */
@Embeddable
public class StatusHasOrderId  implements java.io.Serializable {


     private int statusStatusId;
     private int orderOrderId;

    public StatusHasOrderId() {
    }

    public StatusHasOrderId(int statusStatusId, int orderOrderId) {
       this.statusStatusId = statusStatusId;
       this.orderOrderId = orderOrderId;
    }
   


    @Column(name="status_status_id", nullable=false)
    public int getStatusStatusId() {
        return this.statusStatusId;
    }
    
    public void setStatusStatusId(int statusStatusId) {
        this.statusStatusId = statusStatusId;
    }


    @Column(name="order_order_id", nullable=false)
    public int getOrderOrderId() {
        return this.orderOrderId;
    }
    
    public void setOrderOrderId(int orderOrderId) {
        this.orderOrderId = orderOrderId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StatusHasOrderId) ) return false;
		 StatusHasOrderId castOther = ( StatusHasOrderId ) other; 
         
		 return (this.getStatusStatusId()==castOther.getStatusStatusId())
 && (this.getOrderOrderId()==castOther.getOrderOrderId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStatusStatusId();
         result = 37 * result + this.getOrderOrderId();
         return result;
   }   


}


