package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 6, 2016 12:05:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name="tags")
public class Tags  implements java.io.Serializable {


     private int tagId;
     private String tagEn;
     private String tagAr;
     private Set<MenuItems> menuItems = new HashSet<MenuItems>(0);

    public Tags() {
    }

	
    public Tags(int tagId) {
        this.tagId = tagId;
    }
    public Tags(int tagId, String tagEn, String tagAr, Set menuItems) {
       this.tagId = tagId;
       this.tagEn = tagEn;
       this.tagAr = tagAr;
       this.menuItems = menuItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tag_id", unique=true, nullable=false)
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

    
    @Column(name="tag_en", length=45)
    public String getTagEn() {
        return this.tagEn;
    }
    
    public void setTagEn(String tagEn) {
        this.tagEn = tagEn;
    }

    
    @Column(name="tag_ar", length=45)
    public String getTagAr() {
        return this.tagAr;
    }
    
    public void setTagAr(String tagAr) {
        this.tagAr = tagAr;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="tags_has_menu_items", catalog="mydb", joinColumns = { 
        @JoinColumn(name="tags_tag_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="menu_item_id", nullable=false, updatable=false) })
    public Set<MenuItems> getMenuItems() {
        return this.menuItems;
    }
    
    public void setMenuItems(Set<MenuItems> menuItems) {
        this.menuItems = menuItems;
    }




}


