package com.iti.jet.gp.etbo5ly.model.pojo;
// Generated May 20, 2016 12:10:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name="tags"
    ,catalog="etbo5ly"
)
public class Tags  implements java.io.Serializable {


     private Integer tagId;
     private String tagEn;
     private String tagAr;
     private Set<MenuItems> menuItemses = new HashSet<MenuItems>(0);

    public Tags() {
    }

    public Tags(String tagEn, String tagAr, Set<MenuItems> menuItemses) {
       this.tagEn = tagEn;
       this.tagAr = tagAr;
       this.menuItemses = menuItemses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tag_id", unique=true, nullable=false)
    public Integer getTagId() {
        return this.tagId;
    }
    
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    
    @Column(name="tag_en", length=45)
    public String getTagEn() {
        return this.tagEn;
    }
    
    public void setTagEn(String tagEn) {
        this.tagEn = tagEn;
    }

    
    @Column(name="tag_ar", length=45)
    public String getTagAr() {
        return this.tagAr;
    }
    
    public void setTagAr(String tagAr) {
        this.tagAr = tagAr;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="tags_has_menu_items", catalog="etbo5ly", joinColumns = { 
        @JoinColumn(name="tags_tag_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="menu_item_id", nullable=false, updatable=false) })
    public Set<MenuItems> getMenuItemses() {
        return this.menuItemses;
    }
    
    public void setMenuItemses(Set<MenuItems> menuItemses) {
        this.menuItemses = menuItemses;
    }




}


